# Generated by Django 5.2.12 on 2026-03-13 17:06

import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_title', models.CharField(default='Site Title', max_length=255, verbose_name='Site Title')),
                ('tagline', models.CharField(blank=True, default='Tagline goes here...', max_length=255, null=True, verbose_name='Site Description')),
                ('footer_site_title', models.CharField(default='Footer Site Title', max_length=255, verbose_name='Footer Site Title')),
                ('footer_description', wagtail.fields.RichTextField(blank=True, default='Site Footer Description. Can be left empty!', verbose_name='Footer Description')),
                ('contact_numbers', models.TextField(blank=True, help_text='Enter each contact number in separate line', null=True, verbose_name='Contact Numbers')),
                ('contact_emails', models.TextField(blank=True, help_text='Enter each contact email in separate line', null=True, verbose_name='Contact Emails')),
                ('whatsapp_number', models.CharField(blank=True, help_text='Enter WhatsApp contact number', null=True, verbose_name='WhatsApp Number')),
                ('whatsapp_number_link', models.URLField(blank=True, help_text='Enter WhatsApp contact number link. If left empty, "https://wa.me/<whatsapp_number>" will be used', null=True, verbose_name='WhatsApp Number Link')),
                ('whatsapp_default_message', models.TextField(blank=True, help_text='Default message that is pre-filled in whatsapp message', null=True, verbose_name='Whatsapp Default Message')),
                ('address', models.TextField(blank=True, help_text='Enter the physical address of the business', null=True, verbose_name='Address')),
                ('google_maps_url', models.URLField(blank=True, help_text='Paste the URL of the google maps location', null=True, verbose_name='Google Maps URL')),
                ('google_maps_iframe', models.TextField(blank=True, help_text='Copy HTML and paste the Embed URL from the google maps', null=True, verbose_name='Google Maps Iframe')),
                ('enable_email', models.BooleanField(default=False, help_text='Emails work only if this option is enabled.', verbose_name='Enable Email?')),
                ('email_host', models.CharField(blank=True, help_text='Eg: mail.mydomain.com, smtp.google.com', null=True, verbose_name='Email Host')),
                ('email_port', models.IntegerField(blank=True, help_text='Eg: 587', null=True, verbose_name='Email Port')),
                ('use_tls', models.BooleanField(default=False, help_text='Set whether to use TLS', verbose_name='Use TLS?')),
                ('use_ssl', models.BooleanField(default=False, help_text='Set whether to use SSL', verbose_name='Use SSL?')),
                ('email_host_user', models.CharField(blank=True, help_text='Eg: alerts@mydomain.com, info@mydomain.com', null=True, verbose_name='Email Host User')),
                ('email_host_password', models.CharField(blank=True, help_text='Enter the password of the host user', null=True, verbose_name='Email Host Password')),
                ('enable_razorpay', models.BooleanField(default=False, help_text='Enable this to accept test / live payments', verbose_name='Enable Razorpay?')),
                ('test_api_key', models.CharField(blank=True, help_text='Enter the test API Key generated from Razorpay dashboard', null=True, verbose_name='Test API Key')),
                ('test_api_secret', models.CharField(blank=True, help_text='Enter the test API Secret generated from Razorpay dashboard', null=True, verbose_name='Test API Secret')),
                ('enable_live_mode', models.BooleanField(default=False, help_text='Enable live mode to accept real payments.', verbose_name='Enable Live Mode')),
                ('live_api_key', models.CharField(blank=True, help_text='Enter the live API Key generated from Razorpay dashboard', null=True, verbose_name='Live API Key')),
                ('live_api_secret', models.CharField(blank=True, help_text='Enter the live API Secret generated from Razorpay dashboard', null=True, verbose_name='Live API Secret')),
                ('enable_tax_rates', models.BooleanField(default=False, help_text='Enable tax rates calculation before checkout', verbose_name='Enable Tax Rates?')),
                ('cgst_tax_percent', models.DecimalField(blank=True, decimal_places=2, help_text='Enter the CSGT tax percentage', max_digits=5, null=True, verbose_name='CGST Tax %')),
                ('sgst_tax_percent', models.DecimalField(blank=True, decimal_places=2, help_text='Enter the SSGT tax percentage', max_digits=5, null=True, verbose_name='SGST Tax %')),
                ('igst_tax_percent', models.DecimalField(blank=True, decimal_places=2, help_text='Enter the ISGT tax percentage', max_digits=5, null=True, verbose_name='IGST Tax %')),
                ('add_site_title_to_meta_title', models.BooleanField(default=True, help_text='Set whether to add site title to meta title', verbose_name='Add Site title to Meta title')),
                ('add_spaces', models.BooleanField(default=True, help_text='Set whether to add spaces around the separator. Takes 2 character spaces', verbose_name='Add Spaces')),
                ('separator', models.CharField(default='|', help_text='Eg: |, -', max_length=1, verbose_name='Separator')),
                ('meta_title_length', models.PositiveIntegerField(default=60, help_text='Length of the meta title including meta title or title, spaces, separator, site_title. Extra characters will be truncated', verbose_name='Meta Title Length')),
                ('meta_description_length', models.PositiveIntegerField(default=160, help_text='Length of the meta description. Extra characters will be truncated', verbose_name='Meta Description Length')),
                ('favicon', models.ForeignKey(blank=True, help_text='Icon to be shown in browser tabs, bookmarks, etc.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='common.myimage')),
                ('logo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='common.myimage')),
                ('placeholder_image', models.ForeignKey(blank=True, help_text='This image will be used if there is no image', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='common.myimage')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Script',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('label', models.CharField(help_text='This is for admin identification. Use descriptive names for script', max_length=255, verbose_name='Script Label')),
                ('Script', models.TextField(help_text='Include script tag as well', verbose_name='Script')),
                ('setting', modelcluster.fields.ParentalKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scripts', to='common.sitesettings')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SocialMediaProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('platform', models.CharField(verbose_name='Social Media Name')),
                ('icon_class', models.CharField(blank=True, help_text='Use the Bootstrap Icon class for the social media profile', null=True, verbose_name='Icon Class')),
                ('url', models.URLField(help_text='Enter the complete URL of the profile', verbose_name='Profile Link')),
                ('setting', modelcluster.fields.ParentalKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='social_media_profiles', to='common.sitesettings')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
