# Generated by Django 5.2.12 on 2026-03-14 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_sitesettings_script_socialmediaprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='dimensions_unit',
            field=models.CharField(choices=[('mm', 'mm'), ('cm', 'cm'), ('in', 'in'), ('m', 'm')], default='cm', verbose_name='Dimensions (unit)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='track_stock',
            field=models.BooleanField(default=False, verbose_name='Track stock?'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='weight_unit',
            field=models.CharField(choices=[('kg', 'Kg'), ('g', 'g')], default='kg', verbose_name='Weight (unit)'),
        ),
    ]
