# Generated by Django 5.2.12 on 2026-03-15 07:06

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_simplepage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simplepage',
            name='body',
            field=wagtail.fields.StreamField([('rich_text', 0), ('html', 1), ('home_hero_section', 11)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'required': False}), 1: ('wagtail.blocks.RawHTMLBlock', (), {'label': 'HTML'}), 2: ('wagtail.blocks.RegexBlock', (), {'error_messages': {'invalid': 'Invalid Splide ID format'}, 'help_text': 'CSS ID', 'regex': '^[a-zA-Z][a-zA-Z0-9_-]*$', 'required': False}), 3: ('wagtail.blocks.TextBlock', (), {'default': '{"type": "loop", "autoplay": true, "interval": 3000}', 'help_text': 'Configure banner options as JSON, e.g. {"type": "loop", "autoplay": true}', 'required': False}), 4: ('wagtail.blocks.CharBlock', (), {'max_length': 50}), 5: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 6: ('wagtail.blocks.CharBlock', (), {'required': False}), 7: ('wagtail.blocks.PageChooserBlock', (), {'required': False}), 8: ('wagtail.blocks.StructBlock', [[('image', 5), ('link', 6), ('page', 7)]], {}), 9: ('wagtail.blocks.ListBlock', (8,), {}), 10: ('wagtail.blocks.StructBlock', [[('label', 4), ('slides', 9)]], {}), 11: ('wagtail.blocks.StructBlock', [[('splide_id', 2), ('splide_options', 3), ('banner1', 10), ('banner2', 10), ('banner3', 10)]], {'group': 'Sections'})}),
        ),
    ]
