# Generated by Django 5.2.12 on 2026-03-23 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0010_scheduledmessages_alter_simplepage_body'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ScheduledMessages',
            new_name='ScheduledMessage',
        ),
    ]
