# Generated by Django 5.2.12 on 2026-03-18 00:10

import django.db.models.deletion
import django_countries.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_manager', '0005_alter_cartpage_body_alter_myaccountpage_body_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckoutAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, verbose_name='First name')),
                ('last_name', models.CharField(blank=True, max_length=255, verbose_name='Last name')),
                ('email', models.EmailField(max_length=255, verbose_name='Email Address')),
                ('company', models.CharField(blank=True, max_length=255, verbose_name='Company')),
                ('address1', models.CharField(max_length=255, verbose_name='Address line 1')),
                ('address2', models.CharField(blank=True, max_length=255, verbose_name='Address line 2')),
                ('city', models.CharField(max_length=255, verbose_name='City')),
                ('state', models.CharField(max_length=255, verbose_name='State')),
                ('country', django_countries.fields.CountryField(max_length=2, verbose_name='Country')),
                ('zip', models.CharField(max_length=20, verbose_name='Postcode/Zip')),
                ('landmark', models.CharField(blank=True, max_length=255, verbose_name='Landmark')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Phone number')),
                ('is_billing', models.BooleanField(default=False, help_text='Use as billing address', verbose_name='Billing address')),
                ('is_shipping', models.BooleanField(default=True, help_text='Use as shipping address', verbose_name='Shipping address')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Address',
                'verbose_name_plural': 'Addresses',
                'ordering': ['user', 'is_shipping', 'is_billing'],
            },
        ),
        migrations.DeleteModel(
            name='Address',
        ),
    ]
