# Generated by Django 5.2.12 on 2026-03-18 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_manager', '0006_checkoutaddress_delete_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkoutaddress',
            name='is_billing',
            field=models.BooleanField(default=True, help_text='Use as billing address', verbose_name='Billing address'),
        ),
        migrations.AlterField(
            model_name='checkoutaddress',
            name='is_shipping',
            field=models.BooleanField(default=False, help_text='Use as shipping address', verbose_name='Shipping address'),
        ),
    ]
