# Generated by Django 5.2.12 on 2026-03-18 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_manager', '0007_alter_checkoutaddress_is_billing_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkoutaddress',
            name='is_billing',
            field=models.BooleanField(blank=True, default=False, help_text='Use as billing address', verbose_name='Billing address'),
        ),
        migrations.AlterField(
            model_name='checkoutaddress',
            name='is_shipping',
            field=models.BooleanField(blank=True, default=False, help_text='Use as shipping address', verbose_name='Shipping address'),
        ),
    ]
