# Generated by Django 5.2.12 on 2026-03-18 07:00

import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_manager', '0008_alter_checkoutaddress_is_billing_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkoutaddress',
            name='address1',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Address line 1'),
        ),
        migrations.AlterField(
            model_name='checkoutaddress',
            name='address2',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Address line 2'),
        ),
        migrations.AlterField(
            model_name='checkoutaddress',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='checkoutaddress',
            name='company',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Company'),
        ),
        migrations.AlterField(
            model_name='checkoutaddress',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='checkoutaddress',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True, verbose_name='Email Address'),
        ),
        migrations.AlterField(
            model_name='checkoutaddress',
            name='first_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='First name'),
        ),
        migrations.AlterField(
            model_name='checkoutaddress',
            name='landmark',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Landmark'),
        ),
        migrations.AlterField(
            model_name='checkoutaddress',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Last name'),
        ),
        migrations.AlterField(
            model_name='checkoutaddress',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone number'),
        ),
        migrations.AlterField(
            model_name='checkoutaddress',
            name='state',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='checkoutaddress',
            name='zip',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Postcode/Zip'),
        ),
    ]
