# Generated by Django 5.2.12 on 2026-03-20 07:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_manager', '0009_alter_checkoutaddress_address1_and_more'),
        ('sessions', '0001_initial'),
        ('store_manager', '0020_alter_productimage_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecentlyViewed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Date Updated')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recently_viewed_by_users', to='store_manager.product')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sessions.session')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recently_viewed_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-date_updated',),
            },
        ),
    ]
