# Generated by Django 5.2.12 on 2026-03-15 07:06

import django.db.models.deletion
import django.utils.timezone
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_alter_simplepage_body'),
        ('home', '0002_create_homepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='body',
            field=wagtail.fields.StreamField([('rich_text', 0), ('html', 1), ('home_hero_section', 11)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'required': False}), 1: ('wagtail.blocks.RawHTMLBlock', (), {'label': 'HTML'}), 2: ('wagtail.blocks.RegexBlock', (), {'error_messages': {'invalid': 'Invalid Splide ID format'}, 'help_text': 'CSS ID', 'regex': '^[a-zA-Z][a-zA-Z0-9_-]*$', 'required': False}), 3: ('wagtail.blocks.TextBlock', (), {'default': '{"type": "loop", "autoplay": true, "interval": 3000}', 'help_text': 'Configure banner options as JSON, e.g. {"type": "loop", "autoplay": true}', 'required': False}), 4: ('wagtail.blocks.CharBlock', (), {'max_length': 50}), 5: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 6: ('wagtail.blocks.CharBlock', (), {'required': False}), 7: ('wagtail.blocks.PageChooserBlock', (), {'required': False}), 8: ('wagtail.blocks.StructBlock', [[('image', 5), ('link', 6), ('page', 7)]], {}), 9: ('wagtail.blocks.ListBlock', (8,), {}), 10: ('wagtail.blocks.StructBlock', [[('label', 4), ('slides', 9)]], {}), 11: ('wagtail.blocks.StructBlock', [[('splide_id', 2), ('splide_options', 3), ('banner1', 10), ('banner2', 10), ('banner3', 10)]], {'group': 'Sections'})}),
        ),
        migrations.AddField(
            model_name='homepage',
            name='canonical_url',
            field=models.CharField(blank=True, help_text='If this is the duplicate page and paste the URL of the original page', verbose_name='Canonical URL'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Date Created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homepage',
            name='date_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Date Updated'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='meta_image',
            field=models.ForeignKey(blank=True, help_text='This image will appear when the page is shared', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='common.myimage'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='schema_markup',
            field=models.TextField(blank=True, help_text='Include the script tag as well. SEO Purposes Only!', verbose_name='Schema Markup'),
        ),
    ]
