# Generated by Django 5.2.12 on 2026-03-15 02:02

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0003_sitesettings_dimensions_unit_and_more'),
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('canonical_url', models.CharField(blank=True, help_text='If this is the duplicate page and paste the URL of the original page', verbose_name='Canonical URL')),
                ('schema_markup', models.TextField(blank=True, help_text='Include the script tag as well. SEO Purposes Only!', verbose_name='Schema Markup')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Date Updated')),
                ('body', wagtail.fields.StreamField([('rich_text', 0), ('html', 1)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'required': False}), 1: ('wagtail.blocks.RawHTMLBlock', (), {'label': 'HTML'})})),
                ('meta_image', models.ForeignKey(blank=True, help_text='This image will appear when the page is shared', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='common.myimage')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page', models.Model),
        ),
        migrations.CreateModel(
            name='PostPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('canonical_url', models.CharField(blank=True, help_text='If this is the duplicate page and paste the URL of the original page', verbose_name='Canonical URL')),
                ('schema_markup', models.TextField(blank=True, help_text='Include the script tag as well. SEO Purposes Only!', verbose_name='Schema Markup')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Date Updated')),
                ('body', wagtail.fields.StreamField([('rich_text', 0), ('html', 1)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'required': False}), 1: ('wagtail.blocks.RawHTMLBlock', (), {'label': 'HTML'})})),
                ('meta_image', models.ForeignKey(blank=True, help_text='This image will appear when the page is shared', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='common.myimage')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page', models.Model),
        ),
    ]
