# Generated by Django 5.2.12 on 2026-03-23 06:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_manager', '0005_blogindexpage_featured_image_blogindexpage_views'),
        ('common', '0009_sitesettings_about_page_sitesettings_account_page_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogindexpage',
            name='featured_image',
        ),
        migrations.RemoveField(
            model_name='blogindexpage',
            name='views',
        ),
        migrations.AddField(
            model_name='postpage',
            name='featured_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='common.myimage'),
        ),
        migrations.AddField(
            model_name='postpage',
            name='views',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
