# Generated by Django 5.2.12 on 2026-03-14 09:15

import autoslug.fields
import django.core.validators
import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0002_sitesettings_script_socialmediaprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', autoslug.fields.AutoSlugField(blank=True, editable=False, null=True, populate_from='name')),
                ('type', models.CharField(choices=[('default', 'Default'), ('color', 'Color'), ('image', 'Image')], default='default', max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AttributeValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('value', models.CharField(max_length=50, unique=True)),
                ('color_code', models.CharField(blank=True, max_length=8, null=True)),
                ('slug', autoslug.fields.AutoSlugField(blank=True, editable=False, null=True, populate_from=['attribute__name', 'value'])),
                ('attribute', modelcluster.fields.ParentalKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attribute_values', to='store_manager.attribute')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attribute_images', to='common.myimage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seo_title', models.TextField(max_length=60)),
                ('search_description', models.TextField(max_length=160)),
                ('canonical_url', models.CharField(blank=True, help_text='If this is the duplicate page and paste the URL of the original page', verbose_name='Canonical URL')),
                ('schema_markup', models.TextField(blank=True, help_text='Include the script tag as well. SEO Purposes Only!', verbose_name='Schema Markup')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Date Updated')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255)),
                ('icon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.myimage')),
                ('meta_image', models.ForeignKey(blank=True, help_text='This image will appear when the page is shared', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='common.myimage')),
                ('parent', models.ForeignKey(blank=True, help_text='Select a parent category if this is a subcategory', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='store_manager.category')),
            ],
            options={
                'unique_together': {('slug', 'parent')},
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', autoslug.fields.AutoSlugField(blank=True, editable=False, max_length=255, populate_from='title')),
                ('seo_title', models.TextField(max_length=60)),
                ('search_description', models.TextField(max_length=160)),
                ('canonical_url', models.CharField(blank=True, help_text='If this is the duplicate page and paste the URL of the original page', verbose_name='Canonical URL')),
                ('schema_markup', models.TextField(blank=True, help_text='Include the script tag as well. SEO Purposes Only!', verbose_name='Schema Markup')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Date Updated')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('short_description', wagtail.fields.StreamField([('rich_text', 0), ('html', 1)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'required': False}), 1: ('wagtail.blocks.RawHTMLBlock', (), {'label': 'HTML'})}, null=True)),
                ('description', wagtail.fields.StreamField([('rich_text', 0), ('html', 1)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'required': False}), 1: ('wagtail.blocks.RawHTMLBlock', (), {'label': 'HTML'})}, null=True)),
                ('specifications', wagtail.fields.StreamField([('rich_text', 0), ('html', 1)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'required': False}), 1: ('wagtail.blocks.RawHTMLBlock', (), {'label': 'HTML'})}, null=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_best_selling', models.BooleanField(default=False)),
                ('price_range', models.JSONField(blank=True, default=dict, null=True)),
                ('categories', modelcluster.fields.ParentalManyToManyField(blank=True, help_text='Select all relevant categories', related_name='products', to='store_manager.category')),
                ('meta_image', models.ForeignKey(blank=True, help_text='This image will appear when the page is shared', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='common.myimage')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductVariation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Date Updated')),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('length', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('width', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('height', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('warranty', models.DecimalField(decimal_places=1, max_digits=3, verbose_name='Warranty (years)')),
                ('base_price', models.DecimalField(blank=True, decimal_places=2, help_text='Max. Retail Price', max_digits=10, null=True, verbose_name='MRP')),
                ('sale_price', models.DecimalField(blank=True, decimal_places=2, help_text='Sale price. Can be left empty!', max_digits=10, null=True, verbose_name='Sale Price')),
                ('discount_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('discount_percent', models.DecimalField(decimal_places=0, default=0, max_digits=3)),
                ('stock', models.PositiveBigIntegerField(verbose_name='Stock')),
                ('in_stock', models.BooleanField(blank=True, null=True)),
                ('attributes', modelcluster.fields.ParentalManyToManyField(to='store_manager.attributevalue')),
                ('product', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_variations', to='store_manager.product')),
                ('wishlisted_by', modelcluster.fields.ParentalManyToManyField(related_name='wishlisted_products', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Date Updated')),
                ('rating', models.IntegerField(validators=[django.core.validators.MinLengthValidator(limit_value=1, message='Rating should be at least 1'), django.core.validators.MaxLengthValidator(limit_value=5, message='Rating cannot be greater than 5')])),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store_manager.product')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
