# Generated by Django 5.2.12 on 2026-03-14 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together=set(),
        ),
    ]
