# Generated by Django 5.2.12 on 2026-03-14 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_manager', '0004_alter_category_search_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariation',
            name='sku',
            field=models.CharField(blank=True, null=True, verbose_name='SKU'),
        ),
        migrations.AlterField(
            model_name='productvariation',
            name='warranty',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='Warranty (years)'),
        ),
    ]
