# Generated by Django 5.2.12 on 2026-03-14 11:05

import autoslug.fields
import store_manager.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_manager', '0005_productvariation_sku_alter_productvariation_warranty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attributevalue',
            name='slug',
            field=autoslug.fields.AutoSlugField(blank=True, editable=False, null=True, populate_from=store_manager.models.attribute_value_slug),
        ),
    ]
