# Generated by Django 5.2.12 on 2026-03-14 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_manager', '0006_alter_attributevalue_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariation',
            name='sku',
            field=models.CharField(blank=True, null=True, unique=True, verbose_name='SKU'),
        ),
    ]
