# Generated by Django 5.2.12 on 2026-03-16 07:49

import django.db.models.deletion
import salesman.orders.models
import secrets
import wagtail.fields
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('store_manager', '0010_alter_product_description_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppage',
            name='body',
            field=wagtail.fields.StreamField([('rich_text', 0), ('advanced_rich_text', 5), ('html', 6), ('home_hero_section', 16), ('icon_cards', 21), ('material_cards', 24), ('image_block', 26), ('two_column_image_block', 28), ('mattress_benefits', 30), ('mattress_sizes', 33), ('cta_block', 34)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'required': False}), 1: ('wagtail.blocks.RegexBlock', (), {'error_messages': {'invalid': 'Invalid CSS ID format'}, 'help_text': 'CSS ID', 'regex': '^[a-zA-Z][a-zA-Z0-9_-]*$', 'required': False}), 2: ('wagtail.blocks.RegexBlock', (), {'error_messages': {'invalid': 'Invalid CSS Class format'}, 'help_text': 'CSS Class name', 'regex': '^[a-zA-Z][a-zA-Z0-9_-]*(\\s+[a-zA-Z][a-zA-Z0-9_-]*)*$', 'required': False}), 3: ('wagtail.blocks.TextBlock', (), {'help_text': 'Enter the CSS Style for this block', 'required': False}), 4: ('wagtail.blocks.RichTextBlock', (), {}), 5: ('wagtail.blocks.StructBlock', [[('css_id', 1), ('css_class', 2), ('css_style', 3), ('rich_text', 4)]], {}), 6: ('wagtail.blocks.RawHTMLBlock', (), {'label': 'HTML'}), 7: ('wagtail.blocks.RegexBlock', (), {'error_messages': {'invalid': 'Invalid Splide ID format'}, 'help_text': 'CSS ID', 'regex': '^[a-zA-Z][a-zA-Z0-9_-]*$', 'required': False}), 8: ('wagtail.blocks.TextBlock', (), {'default': '{\n        type: "loop",\n        autoplay: true,\n        interval: 3000,\n    }', 'help_text': 'Configure banner options as JSON, e.g. {\n        type: "loop",\n        autoplay: true,\n        interval: 3000,\n    }', 'required': False}), 9: ('wagtail.blocks.CharBlock', (), {'max_length': 50}), 10: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 11: ('wagtail.blocks.CharBlock', (), {'required': False}), 12: ('wagtail.blocks.PageChooserBlock', (), {'required': False}), 13: ('wagtail.blocks.StructBlock', [[('image', 10), ('link', 11), ('page', 12)]], {}), 14: ('wagtail.blocks.ListBlock', (13,), {}), 15: ('wagtail.blocks.StructBlock', [[('css_id', 1), ('css_class', 2), ('css_style', 3), ('splide_id', 7), ('splide_options', 8), ('label', 9), ('slides', 14)]], {}), 16: ('wagtail.blocks.StructBlock', [[('banner1', 15), ('banner2', 15), ('banner3', 15)]], {'group': 'Sections'}), 17: ('wagtail.blocks.CharBlock', (), {}), 18: ('wagtail.blocks.StreamBlock', [[('rich_text', 0), ('advanced_rich_text', 5), ('html', 6)]], {}), 19: ('wagtail.blocks.StructBlock', [[('icon', 10), ('title', 17), ('description', 18)]], {}), 20: ('wagtail.blocks.ListBlock', (19,), {}), 21: ('wagtail.blocks.StructBlock', [[('css_id', 1), ('css_class', 2), ('css_style', 3), ('cards', 20)]], {'group': 'Sections'}), 22: ('wagtail.blocks.StructBlock', [[('image', 10), ('title', 17), ('description', 18)]], {}), 23: ('wagtail.blocks.ListBlock', (22,), {}), 24: ('wagtail.blocks.StructBlock', [[('css_id', 1), ('css_class', 2), ('css_style', 3), ('heading', 17), ('cards', 23)]], {'group': 'Sections'}), 25: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': False}), 26: ('wagtail.blocks.StructBlock', [[('css_id', 1), ('css_class', 2), ('css_style', 3), ('small_screen_image', 25), ('large_screen_image', 25), ('link', 11), ('page', 12)]], {'group': 'Sections'}), 27: ('wagtail.blocks.ListBlock', (13,), {'max_num': 2}), 28: ('wagtail.blocks.StructBlock', [[('css_id', 1), ('css_class', 2), ('css_style', 3), ('images', 27)]], {'group': 'Sections'}), 29: ('wagtail.blocks.ListBlock', (22,), {'max_num': 3}), 30: ('wagtail.blocks.StructBlock', [[('css_id', 1), ('css_class', 2), ('css_style', 3), ('heading', 17), ('main_image', 10), ('cards_group_1', 29), ('cards_group_2', 29)]], {'group': 'Sections'}), 31: ('wagtail.blocks.StructBlock', [[('image', 10), ('title', 17), ('description', 18), ('link', 11), ('page', 12)]], {}), 32: ('wagtail.blocks.ListBlock', (31,), {}), 33: ('wagtail.blocks.StructBlock', [[('css_id', 1), ('css_class', 2), ('css_style', 3), ('heading', 17), ('cards', 32)]], {'group': 'Sections'}), 34: ('wagtail.blocks.StructBlock', [[('css_id', 1), ('css_class', 2), ('css_style', 3), ('background_image', 10), ('cta_title', 17), ('cta_text', 17), ('icon', 11), ('link', 11), ('page', 12)]], {'group': 'CTA'})}),
        ),
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extra', models.JSONField(blank=True, default=dict, verbose_name='Extra')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Date updated')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
            ],
            options={
                'verbose_name': 'Basket',
                'verbose_name_plural': 'Baskets',
                'ordering': ['-date_created'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.CharField(help_text='A unique order reference.', max_length=128, unique=True, verbose_name='Reference')),
                ('status', models.CharField(default='NEW', help_text='Changing order status might trigger a notification to customer.', max_length=128, verbose_name='Status')),
                ('token', models.CharField(default=secrets.token_urlsafe, help_text="Allow non-authenticated customer to access the order with token. To access order suply a '?token={token}' in url querystring.", max_length=128, unique=True, verbose_name='Token')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('shipping_address', models.TextField(blank=True, verbose_name='Shipping address')),
                ('billing_address', models.TextField(blank=True, verbose_name='Billing address')),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18, verbose_name='Subtotal')),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18, verbose_name='Total')),
                ('_extra', models.JSONField(blank=True, default=dict, verbose_name='Extra')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Date updated')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'ordering': ['-date_created'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.CharField(max_length=128, verbose_name='Product type')),
                ('product_id', models.PositiveIntegerField(null=True, verbose_name='Product id')),
                ('product_data', models.JSONField(blank=True, default=dict, verbose_name='Product data')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Unit price')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Subtotal')),
                ('total', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Total')),
                ('quantity', models.PositiveIntegerField(verbose_name='Quantity')),
                ('_extra', models.JSONField(blank=True, default=dict, verbose_name='Extra')),
                ('order', salesman.orders.models.ParentalForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to=settings.SALESMAN_ORDER_MODEL, verbose_name='Order')),
                ('product_content_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Items',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrderNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='Message')),
                ('public', models.BooleanField(default=False, help_text='Is accessible to the customer?', verbose_name='Public')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('order', salesman.orders.models.ParentalForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to=settings.SALESMAN_ORDER_MODEL, verbose_name='Order')),
            ],
            options={
                'verbose_name': 'Note',
                'verbose_name_plural': 'Notes',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BasketItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.SlugField(max_length=128, verbose_name='Reference')),
                ('product_id', models.PositiveIntegerField(verbose_name='Product id')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Quantity')),
                ('extra', models.JSONField(blank=True, default=dict, verbose_name='Extra')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Date updated')),
                ('basket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to=settings.SALESMAN_BASKET_MODEL, verbose_name='Basket')),
                ('product_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Items',
                'ordering': ['date_created'],
                'abstract': False,
                'unique_together': {('basket', 'ref')},
            },
        ),
        migrations.CreateModel(
            name='OrderPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Amount')),
                ('transaction_id', models.CharField(max_length=128, verbose_name='Transaction ID')),
                ('payment_method', models.CharField(blank=True, max_length=128, verbose_name='Payment method')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('order', salesman.orders.models.ParentalForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.SALESMAN_ORDER_MODEL, verbose_name='Order')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'abstract': False,
                'unique_together': {('order', 'transaction_id')},
            },
        ),
    ]
