# Generated by Django 5.2.12 on 2026-03-17 10:55

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_manager', '0011_alter_shoppage_body_basket_order_orderitem_ordernote_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=wagtail.fields.StreamField([('rich_text', 0), ('advanced_rich_text', 5), ('html', 6), ('product_description_gallery', 12)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'required': False}), 1: ('wagtail.blocks.RegexBlock', (), {'error_messages': {'invalid': 'Invalid CSS ID format'}, 'help_text': 'CSS ID', 'regex': '^[a-zA-Z][a-zA-Z0-9_-]*$', 'required': False}), 2: ('wagtail.blocks.RegexBlock', (), {'error_messages': {'invalid': 'Invalid CSS Class format'}, 'help_text': 'CSS Class name', 'regex': '^[a-zA-Z][a-zA-Z0-9_-]*(\\s+[a-zA-Z][a-zA-Z0-9_-]*)*$', 'required': False}), 3: ('wagtail.blocks.TextBlock', (), {'help_text': 'Enter the CSS Style for this block', 'required': False}), 4: ('wagtail.blocks.RichTextBlock', (), {}), 5: ('wagtail.blocks.StructBlock', [[('css_id', 1), ('css_class', 2), ('css_style', 3), ('rich_text', 4)]], {}), 6: ('wagtail.blocks.RawHTMLBlock', (), {'label': 'HTML'}), 7: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 8: ('wagtail.blocks.CharBlock', (), {'required': False}), 9: ('wagtail.blocks.PageChooserBlock', (), {'required': False}), 10: ('wagtail.blocks.StructBlock', [[('image', 7), ('link', 8), ('page', 9)]], {}), 11: ('wagtail.blocks.ListBlock', (10,), {}), 12: ('wagtail.blocks.StructBlock', [[('css_id', 1), ('css_class', 2), ('css_style', 3), ('images', 11)]], {})}, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='short_description',
            field=wagtail.fields.StreamField([('rich_text', 0), ('advanced_rich_text', 5), ('html', 6), ('product_description_gallery', 12)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'required': False}), 1: ('wagtail.blocks.RegexBlock', (), {'error_messages': {'invalid': 'Invalid CSS ID format'}, 'help_text': 'CSS ID', 'regex': '^[a-zA-Z][a-zA-Z0-9_-]*$', 'required': False}), 2: ('wagtail.blocks.RegexBlock', (), {'error_messages': {'invalid': 'Invalid CSS Class format'}, 'help_text': 'CSS Class name', 'regex': '^[a-zA-Z][a-zA-Z0-9_-]*(\\s+[a-zA-Z][a-zA-Z0-9_-]*)*$', 'required': False}), 3: ('wagtail.blocks.TextBlock', (), {'help_text': 'Enter the CSS Style for this block', 'required': False}), 4: ('wagtail.blocks.RichTextBlock', (), {}), 5: ('wagtail.blocks.StructBlock', [[('css_id', 1), ('css_class', 2), ('css_style', 3), ('rich_text', 4)]], {}), 6: ('wagtail.blocks.RawHTMLBlock', (), {'label': 'HTML'}), 7: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 8: ('wagtail.blocks.CharBlock', (), {'required': False}), 9: ('wagtail.blocks.PageChooserBlock', (), {'required': False}), 10: ('wagtail.blocks.StructBlock', [[('image', 7), ('link', 8), ('page', 9)]], {}), 11: ('wagtail.blocks.ListBlock', (10,), {}), 12: ('wagtail.blocks.StructBlock', [[('css_id', 1), ('css_class', 2), ('css_style', 3), ('images', 11)]], {})}, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='specifications',
            field=wagtail.fields.StreamField([('rich_text', 0), ('advanced_rich_text', 5), ('html', 6), ('product_description_gallery', 12)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'required': False}), 1: ('wagtail.blocks.RegexBlock', (), {'error_messages': {'invalid': 'Invalid CSS ID format'}, 'help_text': 'CSS ID', 'regex': '^[a-zA-Z][a-zA-Z0-9_-]*$', 'required': False}), 2: ('wagtail.blocks.RegexBlock', (), {'error_messages': {'invalid': 'Invalid CSS Class format'}, 'help_text': 'CSS Class name', 'regex': '^[a-zA-Z][a-zA-Z0-9_-]*(\\s+[a-zA-Z][a-zA-Z0-9_-]*)*$', 'required': False}), 3: ('wagtail.blocks.TextBlock', (), {'help_text': 'Enter the CSS Style for this block', 'required': False}), 4: ('wagtail.blocks.RichTextBlock', (), {}), 5: ('wagtail.blocks.StructBlock', [[('css_id', 1), ('css_class', 2), ('css_style', 3), ('rich_text', 4)]], {}), 6: ('wagtail.blocks.RawHTMLBlock', (), {'label': 'HTML'}), 7: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 8: ('wagtail.blocks.CharBlock', (), {'required': False}), 9: ('wagtail.blocks.PageChooserBlock', (), {'required': False}), 10: ('wagtail.blocks.StructBlock', [[('image', 7), ('link', 8), ('page', 9)]], {}), 11: ('wagtail.blocks.ListBlock', (10,), {}), 12: ('wagtail.blocks.StructBlock', [[('css_id', 1), ('css_class', 2), ('css_style', 3), ('images', 11)]], {})}, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=5),
        ),
    ]
