# Generated by Django 5.2.12 on 2026-03-17 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_manager', '0013_alter_review_comment_alter_review_product_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ('-date_created', '-date_updated')},
        ),
    ]
