# Generated by Django 5.2.12 on 2026-03-19 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_manager', '0018_order_razorpay_order_id_order_razorpay_payment_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ratings',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
