# Generated by Django 5.2.12 on 2026-03-19 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_manager', '0019_product_ratings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimage',
            options={'ordering': ['sort_order']},
        ),
    ]
